name: Java CI

on:
  push:
    branches: [ gluon ]
  pull_request:
    branches: [ gluon ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install
